<template>
  <div class="story">
    <p>Would you laugh if I said the most interesting thing to ever happen to me was you?</p>
    <p>I know, I know. A real farm girl, making trips to the castle every week, living in the midst of great times. What’s some lame fairy boy got to offer?</p>
    <p>See, that’s the same thing I asked myself when first we met. I couldn’t forget your face for no reason I can properly explain, though it probably doesn’t hurt that you’re kind of a bad boy. Climbing right past those guards, darting past them and into the castle… it’s enough to set a young maid’s heart a-flutter, let me tell you. More than capable, you were courageous. All that courage is like a drug to me, because I thrive off adventure. I was never really worried about that dumb old princess at first: princesses are supposed to be so staid and boring! How can you have fun inside an old drafty castle? I’ve never been in one personally but I can tell you a farm, with all its muck and hard work, will have infinitely more personality than a bunch of old stone.</p>
    <p>Maybe I shouldn’t have been so wrapped up in taking care of my deadbeat dad. Maybe then I would have had more time to catch your interest. I would always find myself thinking of you when my mind wandered, so imagine my surprise when I looked up from playing with the horses one day and saw your face! I felt so happy I just had to sing, and Epona is my best partner for that. She hated you when she first saw you–maybe she thought you’d steal me away, hm?–but with a little coaxing she just lit right up to you. For a fairy boy you were pretty good with that ocarina, though your sorry excuse for a getup could use some work. I had much more to share with you but I held off on it, figuring you’d come back to see me and Epona. There were games we could play, places we could go, adventures and all sorts of trouble we could get up to… but you never did come back. Not for seven years, anyway. And a lot changed in that time.</p>
    <p>The world got darker, Link. The first I knew of it a tall dark man was at our gates, some Gerudo leader. I don’t know what exactly he said to Ingo but he got puffed up in nothing flat. As soon as the man left Ingo kicked my dad right out and took over the farm! I would have followed my father but my hesitation cost me. I guess he saw me look towards the stables because it didn’t take him two seconds to threaten me through my precious friends. I know, I know. How lame is it for a girl to call animals her friends? But you never did come back. A girl has to take her friends where she can find them.</p>
    <p>And I did my best to care for them, though more often than not it meant taking blows meant for their hides. Most days it hurt to walk but I managed it without a grimace or a glare. I learned early on not to defy Ingo or catch his attention at all, although I never did get why he was so angry all the time. I don’t think me or dad treated him too poorly, but… well, it’s hard to say. And my dad’s off somewhere so I can’t ask him, though I doubt the answer would change much.</p>
    <p>The part that hurt the most was how he changed the horses. He bred and trained them only for racing and shows; he never cared when a horse cut its leg on the high jumps he constructed or when one of his fine racing stallions broke its leg. I saw him kill the poor thing and I couldn’t eat for a week. He beat me extra for that, said if I was going to die on him he’d make me suffer before I went. So I ate. What else was I gonna do?</p>
    <p>They call girls like me damaged goods, you know. That’s what they call girls who’ve been stepped on, beat and spat at, then worked to the bone… and I can’t find it in me to disagree. What’s so different between me and a slave? A courageous person like you would just throw off your shackles but I got snared instead. I think a bit of your courage rubbed off on Epona; she never bowed, not even for a second. Any rider who tried to mount her got pitched off fast. The last one who tried broke his arm in the fall and Epona nearly trampled him dead before Ingo could drag him away. He swore he’d kill my pony for that but I told him if he did I’d run and tell his master what had happened. He beat me extra but I didn’t die and neither did she. I think my nose got broken; it never set quite right and if you look close you can see it angles.</p>
    <p>Can I tell you a secret, Link? The first thing I thought of when he threatened Epona wasn’t that I’d be losing my closest friend… but the possibility you’d never come back if she died. Sometimes I had nightmares about you just leaving without even looking at me when you found out my pony was gone. There were other, nicer dreams too: a girl’s gotta have fantasies and when I needed a hero it was always your face that popped up. I won’t deny spending what time I did get alone thinking about you, and I won’t deny my hands wandering. You’d come sweeping in, depose Ingo and make my dad a good man again and… well, maybe I could teach you some other things this time.</p>
    <p>Maybe you think I’m a dirty girl for thinking like that, but I’ve been dirty all my life, whether from muck or dirt or bad thoughts. A growing girl’s got needs and I don’t doubt you could take care of me just how I want… if only you could see me as a woman. I imagined millions of ways I’d ensnare you when the time finally came, when you returned… but when you finally did I hardly recognized you. You looked like a man, nothing like the boy I remembered. When you made Ingo step down without raising a hand to him first I was so happy I thought I might die.</p>
    <p>Or at least, that was how I felt on the inside. I don’t grin that much anymore, though I think I put a pretty good fake smile on for you. When you talked to me all I could say was how glad I was of Ingo’s new change of heart and how I had absolutely no idea how it could have happened… but you never followed my unspoken question up. I was waiting for you to say “it was me,” and then I’d say “well, you can have anything you want as a reward,” and then… well, it didn’t happen like that. You never even took credit for what you’d done. You never touched me neither, and I guess I can’t blame you. I’m no high-born lady with class and pomp and a big castle, just a girl who was born and will die in the mud with livestock as friends. You left before I could work up the courage to say something, anything, and you never came back once. You took Epona too, so now I’m truly alone. All I have for company is the memory of your big hands and fiery eyes and broad chest… and all I have for the future are fantasies. I could tell you about them if you came and visited–maybe we could play some of them out–but I doubt you’d want that. I doubt you’d want someone like me, someone weak enough to be led around by dumb old Ingo. Some stupid farm girl who’s just damaged goods.</p>
    <p>But at least I’ve got fantasies. And at least I’ve got dreams, even though some of those dreams are nightmares that leave me crying… crying because you’re the most amazing thing to ever happen to me and I let you slip through my fingers.</p>
  </div>
</template>

<script>
</script>

<style lang="scss">
</style>