<template>
  <div class="story">
    <p>I call you the one that got away.</p>
    <p>I used to think that saying was wrong, wretched--it seemed too much like a captor's remark. Now I don't think I'd care how many chains it would take to keep you here, just as long as you did stay... but I think if I managed to lock you away you'd just break free.</p>
    <p>That's sort of your calling, isn't it? To break away and go where you're most needed?</p>
    <p>How horrible that your most wonderful trait would be what keeps you from me.</p>
    <p>You cost me my friends. Did I ever tell you that? No, I can't imagine I ever did; it's not like me to voice my own pain much less use it against someone else. When you were left here in our forest my family didn't want any part of you. Only I, closest to the trees, listened to their whispers and took you in. Once they saw what a good child you were the other Kokiri took a liking to you, but they never forgot what was in their eyes a betrayal. We're taught to fear the outside world, did you know that? Otherwise we'd have Kokiri traveling the world--and none who do make that journey ever come back. I always kept those teachings from you because I had a feeling you'd one day walk Hylia's fields. And I was right, Link, I was right...</p>
    <p>I still remember rushing to meet you on that day you got a fairy all your own. I felt the death of the Deku Tree and I knew your departure wouldn't be far behind. I wish I'd had something to give you besides my old Ocarina, but believe me when I say it was my greatest treasure. Music brings these woods alive and I was always shy around you, Link. I could never bring myself to sing when I knew you'd hear. I always kept a happy tune in my head, even when you left; if nothing else would sustain me, then the music would.</p>
    <p>It was like having my heart torn out when you walked across that bridge. I never realized just how much you meant to me until that moment. The village only got worse, too: I saw the way the others just forgot about your presence and I couldn't speak to them for fear I'd say something vicious. Mido, always jealous, began to think of me as his own now that his chief rival was out of the picture. I thought his advances were unpleasant with you here, but soon I had to take to the woods just to escape from him. The forest is a home, Link. The forest is life, and small grasses waving, and strong trees that never ever bend... am I foolish for thinking, when you came back, you sought a life under these leaves? Like mine? I knew from the second I saw your smiling face the taste of adventure had you hooked, and even as I opened my mouth to sing my most precious song to you I knew it wouldn't be enough to hold you here. Would it have been sufficient a week, two weeks, a month earlier...? I try not to think about it.</p>
    <p>I knew I was just going to hurt myself by sharing that song with you. When you called to speak with me it was always for the benefit of the princess. I don't know what she did to capture your heart, but I can imagine. The allure of a strange girl of noble birth is strong, right? And I'm just plain Saria with no chest and a bad smile and a bunch of twigs for a roof. Honestly, I can't blame you for choosing her... but I can wish you chose differently. And I can dream it. Sometimes dreams are enough, even when the boy you love is talking with such excitement about the adventures he's going on far, far away from you. Would that I could chase after you, but I've always known I'd never leave the forest. I've known it as an undeniable truth, like the fact that the sun will rise every day and the fact that you will never be mine. So when you asked me about a quest for the princess, I could pretend it was enough just to hear your voice.</p>
    <p>But even that stopped. One day I couldn't feel you anymore and though I hoped for a hint, or a sign the next week and then the next... nothing ever came. It was like you disappeared off the face of Hyrule, and no matter how hard I tried to find you it was useless.</p>
    <p>The world got worse in those seven years you were missing, Link. The world got much worse. Even the forest I knew so well became frightening and dark. Shadows crept from the night to infest the brightest parts of my favorite clearings, driving me further and further back into the sacred Forest Temple. I found the deepest, smallest corner I could reach and I hid there in nameless fear of a man I did not know. I stayed there for longer than I could tell; we Kokiri cannot die of hunger or thirst--the forest provides--but if it was possible to die of loneliness I would have. It was an unspeakable joy to feel you again, see you again... but that brought a kind of pain with it as well.</p>
    <p>Perhaps I still held out a faint hope of capturing your heart, seven years later, because it still felt like my heart was breaking when I saw you were lost to me. When you played on an ocarina that wasn't mine--what did you do with my treasure, toss it away in favor of a shinier toy?--when you reached out for that gold-haired girl in disguise, when I saw you big and strapping and old... really, who could blame you for choosing the princess over me? I'm just plain, young Saria with no hips to speak of and a child's body and a bland personality. Who could blame you for choosing a woman over a girl? And I think I am a girl; I think I am a child and perhaps I always will be one. Because when I look at you I feel so small, so insignificant that I just want to curl up and cry... and when I can't help but imagine your arms encircling me, comforting me, it makes me feel a little bit better before it makes me feel a whole lot worse. The forest is a home, but it's not a lover and it's not a friend.</p>
    <p>And yet, even if I did somehow steal you away from princess Zelda I know you'd never really be mine. In your future I know there are faraway lands and strange people and monsters and things I've never heard of... and my world is just the sunlight shining through the leaves in woods that never change. Did you know that the Deku Tree sapling is the first green thing to really grow in this forest, Link? Sure, grass grows and bushes grow but everything is stunted. Everything stops at a certain height or length or width; that's why the Deku Tree is so special. I wish I was special like the sapling, Link... I wish I could grow like you and leave this forest and call you mine. But I can do none of those things and so once more I am simple, small Saria.</p>
    <p>Perhaps it's enough to support you from afar, Link. Perhaps it's enough to guide your way to the evil so you can fulfil your destiny to destroy it... but in some ways I wish you'd fail. I hear the rest of the world is as badly affected as the forest was before you freed it: perhaps you would come back here when Ganondorf bested you. Is it wrong to dream of comforting you in my own arms, soothing your wounds and nursing you back to health? Is it wrong to wish the whole of Hyrule burned around us so you'd never have reason to leave?</p>
    <p>And yet I know that would destroy the very nature of who you are. I know you're more than a hero; you're THE Hero, the one destined to save us or die trying. That's in your fate and the forest is in mine. Neither of us can be anything but what we are, and so I like to think it doesn't hurt as much as it would if we had a choice.</p>
    <p>I'll always be your friend and ally, Link, no matter whose ocarina you choose to play on. I'll always be waiting here, ready to listen to whatever you have to say.</p>
    <p>Remember that much when you defeat the evil plaguing this land. Come back to me, even if it's just for a day or an hour or a minute at a time. Just so I can see your face and imagine what it would be like to have those arms around my childish frame.</p>
    <p>Promise?</p>
  </div>
</template>

<script>
</script>

<style lang="scss">
</style>